version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: portfolio-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      portfolio-network: {}
networks:
  portfolio-network:
    driver: bridge
volumes:
  mongodb-data:
